# Audiobook Bob — audiobook CD ripper.
# Copyright (C) 2026 Chris Kuper
# Licensed under the GNU General Public License v3.0 or later.
# See the LICENSE file in the project root for details.
"""UI asset loading: real files in development, generated bundle when frozen.

The HTML/CSS/JS live as separate editable files in abscd/ui/. They are always
delivered to pywebview as ONE inline string (no file:// URLs, nothing external):

- Development: load_html() reads the three files and inlines on the fly, so
  editing ui/*.* and relaunching is enough — no build step in the loop.
- Packaging:   tools/build_ui.py calls build_bundle() to write ui_bundle.py,
  which a frozen app imports when the source files are absent.

This module must not import pywebview: the build step runs without it.
"""

from __future__ import annotations

from pathlib import Path

UI_DIR = Path(__file__).resolve().parent / "ui"
BUNDLE_PATH = Path(__file__).resolve().parent / "ui_bundle.py"

CSS_TAG = '<link rel="stylesheet" href="style.css">'
JS_TAG = '<script src="app.js"></script>'


def inline_html(html: str, css: str, js: str) -> str:
    """Replace the two local asset tags with inline <style>/<script> blocks."""
    if CSS_TAG not in html or JS_TAG not in html:
        raise RuntimeError(
            "index.html no longer contains the expected style.css/app.js tags; "
            "update CSS_TAG/JS_TAG in uiassets.py to match.")
    html = html.replace(CSS_TAG, "<style>\n" + css + "\n</style>")
    html = html.replace(JS_TAG, "<script>\n" + js + "\n</script>")
    return html


def _read(name: str) -> str:
    return (UI_DIR / name).read_text(encoding="utf-8")


def load_html() -> str:
    """The single inline HTML string handed to webview.create_window()."""
    if UI_DIR.is_dir():
        return inline_html(_read("index.html"), _read("style.css"), _read("app.js"))
    from . import ui_bundle  # generated by tools/build_ui.py
    return ui_bundle.HTML


def build_bundle() -> Path:
    """Package-time step: bake the inlined HTML into an importable module."""
    html = inline_html(_read("index.html"), _read("style.css"), _read("app.js"))
    BUNDLE_PATH.write_text(
        '"""GENERATED by tools/build_ui.py — do not edit; edit abscd/ui/* '
        'instead."""\n\nHTML = ' + repr(html) + "\n",
        encoding="utf-8")
    return BUNDLE_PATH
